apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: demo-rg
  namespace: crossplane
spec:
  location: East US
  reclaimPolicy: Delete
  providerConfigRef:
    name: azure-provider