apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: demo-rg
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    location: East US
  providerConfigRef:
    name: azure-provider
