apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tooling
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/tbenedek92/platform-demo.git
  - https://kubernetes.github.io/ingress-nginx
  - https://kubernetes-sigs.github.io/metrics-server/
  - https://charts.crossplane.io/stable
  - https://bitnami-labs.github.io/sealed-secrets
status: {}
