apiVersion: v1
stringData:
  name: ingress-nginx
  project: tooling
  type: helm
  url: https://kubernetes.github.io/ingress-nginx
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  namespace: argocd
  name: ingress-nginx-repo
type: Opaque
