apiVersion: v1
stringData:
  name: crossplane
  project: tooling
  type: helm
  url: https://charts.crossplane.io/stable
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  namespace: argocd
  name: crossplane-repo
type: Opaque
