apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-config
  namespace: argocd
  labels:
    tool: crossplane
    host-cloud: aws
spec:
  project: tooling
  source:
    repoURL: 'https://github.com/tbenedek92/platform-demo.git'
    path: aws/crossplane/provider/config
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
