apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  sources:
  - chart: sealed-secrets
    repoURL:  https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.13.0
    helm:
      valueFiles:
      - $values/aws/charts/sealed-secrets/values.yaml
  - repoURL: 'https://github.com/tbenedek92/platform-demo.git'
    targetRevision: main
    ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
