apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  sources:
  - chart: metrics-server
    repoURL:  https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.11.0
    helm:
      valueFiles:
      - $values/aws/charts/metrics-server/values.yaml
  - repoURL: 'https://github.com/tbenedek92/platform-demo.git'
    targetRevision: main
    ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
